#!/usr/bin/env bash
#Configurating and managing DNS domains so it points to the load balancer IP

#Creating the vars
printsub()
{
	printf "is a "; dig "$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
	printf " record and points to " ; dig "$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
	echo ""
}

if [ -z "$2" ]
then
printf "The subdomain www "
printsub "www.$1"

printf "The subdomain lb-01 "
printsub "lb-01.$1"

printf "The subdomain web-01 "
printsub "web-01.$1"

printf "The subdomain web-02 "
printsub "web-02.$1"

else
	printf "The subdomain %s " "$2"
	printsub "$2.$1"
fi
