#!/usr/bin/env bash
#bash script that transfers a file from our clinet to a server
#usage: Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ "$#" -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	PATHFILE=$1
	IP=$2
	USER=$3
	PATHKEY=$4

	scp -o StrictHostKeyChecking=no -i "$PATHKEY" "$PATHFILE" "$USER@$IP":~/
fi
