#!/usr/bin/env bash
#What you have to do here, is to install nginx, and then go to the html file,
#delete everything that is inside the body, and the write "Hello World" inside

sudo apt update
sudo apt install nginx
cd /var/www/html
sudo chmod 777 index.nginx-debian.html
echo Hello World > index.nginx-debian.html
sudo service nginx restart
