#!/usr/bin/env bash
# configurate nginx redirection

sudo apt update
sudo apt-get -y install nginx
cd /var/www/html
sudo chmod 777 index.nginx-debian.html
echo Hello World > index.nginx-debian.html
sed -i "%server_name _;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
