#!/usr/bin/env bash
#Script that install and configure HAproxy on your lb-01 server

sudo apt update
sudo apt-get install -y haproxy=2.4.*
echo "listen 4375-lb-01 " | sudo tee -a /etc/haproxy/haproxy.cfg
echo "bind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4375-web-01 54.226.217.39:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4375-web-02 34.229.176.58:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
