#!/usr/bin/env bash
#Script that install and configure HAproxy on your lb-01 server

sudo apt update
sudo apt-get install -y haproxy
echo "listen 4367-lb-01 " | sudo tee -a /etc/haproxy/haproxy.cfg
echo "bind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4367-web-01 35.175.220.232:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4367-web-02 54.221.168.160:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
