#!/usr/bin/env bash
#Script that install and configure HAproxy on your lb-01 server

sudo apt update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get install -y haproxy=2.4.*
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo echo "backend nginx_pool" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "server 4367-web-01 35.175.220.232:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "server 4367-web-02 54.221.168.160:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
