#!/usr/bin/env bash
# Script that backup MYSQL dump and creates a compressed archive out of it

sudo mysqldump -uroot -p"$1" --all-databases | sudo tee backup.sql
tar -cvzf "$(date '+%d-%m-%Y').tar.gz" backup.sql
