#!/usr/bin/env bash
# Script that enters nginx as nginx user
pkill apache2
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo -u nginx -c 'service nginx restart'
