#!/usr/bin/env bash
# Script that enters nginx as nginx user
sudo pkill apache2
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
su nginx -c 'service nginx restart'
